name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  get_packages:
    name: Get Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - uses: actions/checkout@v4

      - name: Get Packages
        id: get_json
        run: echo "json=$(bin/get-packages)" >> $GITHUB_OUTPUT

      - name: Output Packages
        run: echo "${{ steps.get_json.outputs.json }}"
    outputs:
      matrix: ${{ steps.get_json.outputs.json }}

  phpunit:
    runs-on: ${{ matrix.os }}
    needs: get_packages
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        package: ${{ fromJson(needs.get_packages.outputs.matrix) }}
        php:
          - 8.3
        stability:
          - prefer-stable

    name: Run Tests - P${{ matrix.php }} - ${{ matrix.package.name }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, pcntl, fileinfo
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          cd "${{ matrix.package.directory }}"
          composer global require phpunit/phpunit:^11.3
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: phpunit -c "${{ matrix.package.directory }}/phpunit.xml" --coverage-clover build/reports/clover.xml